SELECT * FROM RAWDATA WHERE VERSION ='13.9.506.4846';

SELECT count(*) FROM RAWDATA ;

SELECT count(*) FROM SUMMONER s ;

SELECT * FROM SUMMONER s ;

SELECT * FROM CHAMPDATA 

SELECT count(*) FROM CHAMPION_ITEM_BOOTS ;

SELECT count(*) FROM CHAMPION_ITEM_START cis  ;

SELECT * FROM CHAMPDATA
WHERE CHAMP_TITLE LIKE '%Tank%'
--   OR CHAMP_TITLE LIKE '%Fighter%';

SELECT *FROM SUMMONER s WHERE SUMMONER_TIER = 'MASTER';

SELECT count(*) FROM LOL_CH lc ;

SELECT count(*) FROM LOL_GM lg ;

SELECT count(*) FROM LOL_MASTER lm  ;

SELECT * FROM CHAMPION_ITEM_BOOTS cib  WHERE  CHAMP_ID = 81;

SELECT *  FROM CHAMPDATA c ;

SELECT * FROM CHAMPION_INFO ci WHERE CHAMP_ID = 1;

SELECT c.CHAMP_ID ,c.CHAMP_KEY ,c.CHAMP_NAME ,c.CHAMP_ICON , ci.LANE ,ci.WIN_RATE ,ci.PICK_RATE ,ci.BAN_RATE  FROM CHAMPDATA c LEFT JOIN CHAMPION_INFO ci ON c.CHAMP_ID = ci.CHAMP_ID WHERE ci.LANE = 'TOP' and c.CHAMP_KEY ='Sett';

SELECT c.CHAMP_ID, c.CHAMP_KEY, c.CHAMP_NAME, c.CHAMP_ICON, ci.LANE, ci.WIN_RATE, ci.PICK_RATE, ci.BAN_RATE
FROM CHAMPDATA c
LEFT JOIN CHAMPION_INFO ci ON c.CHAMP_ID = ci.CHAMP_ID
WHERE ci.LANE = 'MIDDLE'
ORDER BY ci.WIN_RATE DESC;

SELECT c.CHAMP_ID ,c.CHAMP_KEY ,c.CHAMP_NAME ,c.CHAMP_ICON , ci.LANE  FROM CHAMPDATA c LEFT JOIN CHAMPION_INFO ci ON c.CHAMP_ID = ci.CHAMP_ID WHERE  c.CHAMP_ID ='517' AND ci.LANE ='TOP';

SELECT c.CHAMP_ID ,c.CHAMP_KEY ,c.CHAMP_NAME ,c.CHAMP_ICON , ci.LANE  FROM CHAMPDATA c LEFT JOIN CHAMPION_INFO ci ON c.CHAMP_ID = ci.CHAMP_ID WHERE  lane = 'MIDDLE';

SELECT CHAMP_NAME, CHAMP_ICON  FROM CHAMPDATA WHERE CHAMP_NAME  LIKE '%자%';

SELECT c.CHAMP_ID ,c.CHAMP_KEY ,c.CHAMP_NAME ,c.CHAMP_ICON , ci.LANE ,ci.WIN_RATE ,ci.PICK_RATE ,ci.BAN_RATE  FROM CHAMPDATA c LEFT JOIN CHAMPION_INFO ci ON c.CHAMP_ID = ci.CHAMP_ID;


SELECT * FROM CHAMPION_SKILL cs  WHERE CHAMP_ID = 119 ;

SELECT * FROM CHAMPION_RUNE cr WHERE CHAMP_ID = 119;

SELECT RUNETYPE_CORE  FROM CHAMPION_RUNE cr;

SELECT * FROM CHAMPION_RUNE cr WHERE CHAMP_ID = 517 AND LANE ='JUNGLE';

SELECT * FROM RUNETYPE  ;

SELECT * FROM RUNE ;

SELECT * FROM RUNESHARD ;


SELECT RUNE_ID,RUNETYPE_ID, RUNE_ICON ,RUNE_SHORTDESC ,RUNE_LONGDESC  FROM RUNE r ;



/* 룬 이미지 꺼내기 위한 조인 */
SELECT rt.RUNETYPE_ID, rt.RUNETYPE_NAME ,rt.RUNETYPE_KEY ,rt.RUNETYPE_ICON ,r.RUNE_ID ,r.RUNE_NAME , r.RUNE_KEY ,r.RUNE_ICON ,r.RUNE_SHORTDESC ,r.RUNE_LONGDESC  FROM RUNETYPE rt 
LEFT JOIN RUNE r ON rt.RUNETYPE_ID  = r.RUNETYPE_ID 
WHERE rt.RUNETYPE_ID = '8000' OR r.RUNE_ID = '8005';



SELECT COUNT(*) FROM CHAMPION_RUNE cr 
WHERE CHAMP_ID = '517' 
ORDER BY GAME_COUNT DESC;

-- 해당챔피언이 간 룬 게임순으로 
SELECT *
FROM (
  SELECT *
  FROM CHAMPION_RUNE cr
  WHERE CHAMP_ID = '517' AND LANE = 'MIDDLE'
  ORDER BY GAME_COUNT DESC
) WHERE ROWNUM <= 2;



--챔피언 이름중  "가" 가들어간 챔피언 검색 
SELECT c.CHAMP_ID,c.CHAMP_NAME, c.CHAMP_ICON,ci.LANE FROM
CHAMPDATA c
LEFT JOIN CHAMPION_INFO ci ON c.CHAMP_ID = ci.CHAMP_ID
WHERE c.CHAMP_NAME LIKE '%가%' ;

-- 이름 검색한 챔피언 이미지 뽑기
SELECT c.CHAMP_ID, c.CHAMP_NAME, c.CHAMP_ICON, MAX(ci.LANE) AS LANE
FROM CHAMPDATA c
LEFT JOIN CHAMPION_INFO ci ON c.CHAMP_ID = ci.CHAMP_ID
GROUP BY c.CHAMP_ID, c.CHAMP_NAME, c.CHAMP_ICON




-- 매치업 테이블 생성
CREATE TABLE CHAMPION_MATCHUP (
    lane VARCHAR2(20),
    champion_id NUMBER,
    kda NUMBER(10, 2),
    killParticipation NUMBER(10, 2),
    totalDamageDealtToChampions NUMBER(10, 2),
    opponent_id NUMBER,
    opponent_kda NUMBER(10, 2),
    opponent_killParticipation NUMBER(10, 2),
    opponent_totalDamageDealtToChampions NUMBER(10, 2),
    count NUMBER,
    total_win NUMBER,
    win_rate NUMBER(10, 2)
);

-- 해당 챔피언이 간 아이템 빌드 게임 수 순으로 정렬
SELECT * FROM (SELECT * FROM CHAMPION_ITEM_BUILD WHERE CHAMP_ID = 517 AND lane = 'MIDDLE' ORDER BY PICK_RATE DESC) WHERE rownum <=2 ;

SELECT * FROM (SELECT * FROM CHAMPION_SKILL cs WHERE
		CHAMP_ID = 17 AND lane = 'TOP' ORDER BY WIN_RATE DESC FETCH FIRST 1 ROWS ONLY)
		c
		INNER JOIN CHAMPSKILL cs ON(c.CHAMP_ID = cs.CHAMP_ID) ORDER BY
		SKILL_ID;

-- 해당챔피언으로 간 스펠
SELECT * FROM CHAMPION_SPELL cs 
WHERE CHAMP_ID = 517 AND LANE ='MIDDLE'
ORDER BY GAME_COUNT DESC;

SELECT *
FROM (
  SELECT *
  FROM CHAMPION_SPELL cs
  WHERE CHAMP_ID = 98 AND LANE = 'MIDDLE'
  ORDER BY GAME_COUNT DESC
)
WHERE ROWNUM <= 2;

SELECT *
		FROM (
		SELECT *
		FROM CHAMPION_RUNE cr
		WHERE CHAMP_ID = 50 AND LANE = 'MIDDLE'
		ORDER BY GAME_COUNT DESC
		) WHERE ROWNUM <= 2;


-- 해당 챔피언과 매치업 조회 승률순으로 정렬 3개 뽑기
SELECT *
FROM (
  SELECT *
  FROM CHAMPION_MATCHUP
  WHERE CHAMP_ID_X = '35' AND LANE = 'TOP' AND CHAMP_ID_Y ='126'
  ORDER BY MATCHUP_WIN_RATE DESC
) 
WHERE ROWNUM <= 3;



SELECT *
		FROM (
		  SELECT *
		  FROM CHAMPION_MATCHUP
		  WHERE CHAMP_ID_X = 98 AND LANE = 'TOP'
		  ORDER BY MATCHUP_WIN_RATE DESC
		) 
		WHERE ROWNUM <= 20
		
SELECT *
		FROM (
		  SELECT *
		  FROM CHAMPION_MATCHUP
		  WHERE CHAMP_ID_X = 517 AND LANE = 'MIDDLE' AND MATCHUP_COUNT >= 10
		  ORDER BY MATCHUP_WIN_RATE asc
		) 
		WHERE ROWNUM <= 3
		





-- 카운터 챔피언 뽑아내는 쿼리문
SELECT *
FROM (
    SELECT cm.LANE AS LANE, cm.CHAMP_ID_X  ,cm.CHAMP_ID_Y 
    FROM CHAMPION_INFO ci
    INNER JOIN CHAMPION_MATCHUP cm ON ci.CHAMP_ID = cm.CHAMP_ID_X AND ci.LANE = cm.LANE
    WHERE ci.CHAMP_ID = 517 AND ci.LANE = 'MIDDLE' AND cm.MATCHUP_COUNT >= 20
    ORDER BY cm.MATCHUP_WIN_RATE ASC
) c1
INNER JOIN CHAMPDATA c2
ON c1.champ_id_y = c2.CHAMP_ID 
WHERE ROWNUM <= 3;


SELECT c.CHAMP_ID, c.CHAMP_KEY, c.CHAMP_NAME, c.CHAMP_ICON,
       ci.LANE AS lane, ci.WIN_RATE, ci.PICK_RATE, ci.BAN_RATE,ci.game_count
FROM CHAMPDATA c
inner JOIN CHAMPION_INFO ci ON c.CHAMP_ID = ci.CHAMP_ID
WHERE ci.LANE = 'TOP'
ORDER BY game_count DESC;


-- 해당 챔피언과 만난 챔프들 리스트 뽑기
SELECT c.CHAMP_ID, c.CHAMP_KEY, c.CHAMP_NAME, c.CHAMP_ICON,
       ci.LANE AS lane, ci.WIN_RATE, ci.PICK_RATE, ci.BAN_RATE, ci.game_count
FROM CHAMPDATA c
INNER JOIN CHAMPION_INFO ci ON c.CHAMP_ID = ci.CHAMP_ID
WHERE ci.LANE = 'TOP'
ORDER BY ci.game_count DESC
FETCH FIRST 20 ROWS ONLY;

SELECT c.CHAMP_ID, c.CHAMP_KEY, c.CHAMP_NAME, c.CHAMP_ICON,
       ci.LANE AS lane, ci.WIN_RATE, ci.PICK_RATE, ci.BAN_RATE
FROM CHAMPDATA c
LEFT JOIN CHAMPION_INFO ci ON c.CHAMP_ID = ci.CHAMP_ID
WHERE ci.LANE = 'TOP'
ORDER BY ci.WIN_RATE asc
FETCH FIRST 20 ROWS ONLY;
