CREATE OR REPLACE VIEW CHAMPNAME AS (
    SELECT E.CHAMPIONID CHAMPID, E.CHAMPION_NAME EN_NAME, K.CHAMPION_NAME_KR KR_NAME
    FROM CHAMPION_NAME E
    JOIN CHAMPION_NAME_KR K
    ON E.CHAMPIONID = K.CHAMPIONID
);