DELETE FROM CHAMPION_INFO;
DELETE FROM CHAMPION_ITEM_BOOTS;
DELETE FROM CHAMPION_ITEM_BUILD;
DELETE FROM CHAMPION_ITEM_START;
DELETE FROM CHAMPION_MATCHUP;
DELETE FROM CHAMPION_RUNE;
DELETE FROM CHAMPION_SKILL;
DELETE FROM CHAMPION_SPELL;